### PR TITLE
Add key press, consistency, and more aesthetically pleasing

### PR DESCRIPTION
**Pull request by ChaiTeaNunes**

### CODE REVIEW

**Comment by ChaiTeaNunes** [comment]
@ak65234 Actually, since this is javascript and not c++ etc, I feel single quotes are better

**Comment by ak65234** [comment]
@Thaiberius To each his own.

**Comment by ChaiTeaNunes** [comment]
@ak65234 So should I change that or nah?

**Comment by ak65234** [comment]
@Thaiberius I prefer double quotes; you prefer single quotes.  I can do either one, but we should make up our minds before the code grows too much.
I think it will depend more on the necessity of character escaping, such as:
<code>'"'</code> vs <code>"\""</code>
and
<code>"'"</code> vs <code>'\''</code>

**Comment by ChaiTeaNunes** [comment]
@ak65234

" \" " For quotes in game. We'll do C++ stuff (' ' for chars and " " for strings)
'c' For chars
"String" For Strings.

**Comment by ak65234** [comment]
@Thaiberius Now we have our convention.

By the way, C++ is based off of C which has the same convention.  Java (also C based) also follows this format.  This is the consistency I was referring to.

The idea is to be able to work in any language and use the same format.

**Comment by ChaiTeaNunes** [comment]
@ak65234 Now I did what you did with index so Will can get it in 1 pull

**Comment by willibles** [comment]
Huh, can't merge. Guys I'm adding you as contributors

**Comment by ChaiTeaNunes** [comment]
thanks will. I'll figure it out

**Comment by ChaiTeaNunes** [comment]
Well it doesn't work anyways

**Pull request closed without merging**
