### PR TITLE
index.html - Added Charset and Restructured HTML

### PR DESCRIPTION
**Pull request by ak65234**
Alphabetized tag attributes, added a charset, moved script to head, and added types to script and css for browser compatibility.

### CODE REVIEW

**Comment by ak65234** [comment]
Closed because @Thaiberius incorporated it into his pull request.

**Comment by ak65234** [comment]
Reopened because mine was more complete.

**Comment by ChaiTeaNunes** [comment]
Wait more complete?

**Comment by ChaiTeaNunes** [comment]
ah.

**Comment by willibles** [comment]
Please wait until I have a bit more work done. The game uses KiwiJS and Bootstrap, so by the next push, the code will be very different. Thanks for helping! I just don't know if those enhancements will work with Bootstrap.

**Comment by ak65234** [comment]
I looked at Bootstrap and KiwiJS...the structure is compatible as far as I could tell.

**Comment by willibles** [comment]
I check, I merged, I conquered. XD

**Pull request merged**
